<?php

namespace Nativephp\MobileWidgets\Commands;

use Native\Mobile\Plugins\Commands\NativePluginHookCommand;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;

class PostCompileCommand extends NativePluginHookCommand
{
    private const AUTOGEN_MARKER = 'NATIVEPHP_WIDGETS_AUTOGENERATED';

    private const TARGET_NAME = 'NativePHPWidgetsExtension';

    protected $signature = 'nativephp:widgets:post-compile';

    protected $description = 'Post-compile tasks for Widgets plugin';

    public function handle(): int
    {
        if (! $this->isIos()) {
            return self::SUCCESS;
        }

        $pbxprojPath = $this->locatePbxprojPath();

        if (! $pbxprojPath) {
            $this->warn('No iOS project.pbxproj found in build output; skipping WidgetKit target injection.');

            return self::SUCCESS;
        }

        $content = file_get_contents($pbxprojPath);

        if ($content === false) {
            $this->warn('Unable to read iOS project.pbxproj; skipping WidgetKit target injection.');

            return self::SUCCESS;
        }

        if (str_contains($content, self::AUTOGEN_MARKER) || str_contains($content, '/* '.self::TARGET_NAME.' */ = {')) {
            $this->info('WidgetKit target already present in iOS project.');

            return self::SUCCESS;
        }

        $updated = $this->injectWidgetTarget($content);

        if ($updated === null) {
            $this->warn('Unable to inject WidgetKit target automatically; project format did not match expected anchors.');

            return self::SUCCESS;
        }

        if (file_put_contents($pbxprojPath, $updated) === false) {
            $this->warn('Failed writing updated iOS project.pbxproj; WidgetKit target injection was not saved.');

            return self::SUCCESS;
        }

        $this->info('Injected WidgetKit app extension target into iOS project.pbxproj.');

        return self::SUCCESS;
    }

    private function locatePbxprojPath(): ?string
    {
        $buildPath = $this->buildPath();

        if (! is_dir($buildPath)) {
            return null;
        }

        $direct = glob($buildPath.'/*.xcodeproj/project.pbxproj');

        if (is_array($direct) && count($direct) > 0) {
            return $direct[0];
        }

        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($buildPath, RecursiveDirectoryIterator::SKIP_DOTS)
        );

        foreach ($iterator as $file) {
            if (! $file->isFile() || $file->getFilename() !== 'project.pbxproj') {
                continue;
            }

            $parent = dirname((string) $file->getPathname());

            if (str_ends_with($parent, '.xcodeproj')) {
                return (string) $file->getPathname();
            }
        }

        return null;
    }

    private function injectWidgetTarget(string $content): ?string
    {
        $projectObjectId = $this->detectProjectObjectId($content);
        $mainTargetName = $this->detectMainTargetName($content) ?? 'NativePHP';

        if ($projectObjectId === null) {
            return null;
        }

        $ids = [
            'buildFile' => $this->objectId('build-file'),
            'containerProxy' => $this->objectId('container-item-proxy'),
            'fileRef' => $this->objectId('file-reference'),
            'syncGroup' => $this->objectId('sync-group'),
            'copyPhase' => $this->objectId('copy-files-phase'),
            'frameworksPhase' => $this->objectId('frameworks-phase'),
            'resourcesPhase' => $this->objectId('resources-phase'),
            'sourcesPhase' => $this->objectId('sources-phase'),
            'targetDependency' => $this->objectId('target-dependency'),
            'target' => $this->objectId('native-target'),
            'debugConfig' => $this->objectId('debug-config'),
            'releaseConfig' => $this->objectId('release-config'),
            'configList' => $this->objectId('config-list'),
        ];

        $targetName = self::TARGET_NAME;
        $appexName = $targetName.'.appex';
        $bundleId = $this->appId().'.widgets';
        $appGroup = 'group.'.$this->appId().'.widgets';

        $result = $this->insertBeforeMarker(
            $content,
            '/* End PBXBuildFile section */',
            "\t\t{$ids['buildFile']} /* {$appexName} in Embed App Extensions */ = {isa = PBXBuildFile; fileRef = {$ids['fileRef']} /* {$appexName} */; settings = {ATTRIBUTES = (RemoveHeadersOnCopy, ); }; };\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        $result = $this->insertBeforeMarker(
            $content,
            '/* End PBXContainerItemProxy section */',
            "\t\t{$ids['containerProxy']} /* PBXContainerItemProxy */ = {\n"
            ."\t\t\tisa = PBXContainerItemProxy;\n"
            ."\t\t\tcontainerPortal = {$projectObjectId} /* Project object */;\n"
            ."\t\t\tproxyType = 1;\n"
            ."\t\t\tremoteGlobalIDString = {$ids['target']};\n"
            ."\t\t\tremoteInfo = {$targetName};\n"
            ."\t\t};\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        $result = $this->insertBeforeMarker(
            $content,
            '/* End PBXFileReference section */',
            "\t\t{$ids['fileRef']} /* {$appexName} */ = {isa = PBXFileReference; explicitFileType = \"wrapper.app-extension\"; includeInIndex = 0; path = {$appexName}; sourceTree = BUILT_PRODUCTS_DIR; };\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        $result = $this->insertBeforeMarker(
            $content,
            '/* End PBXFileSystemSynchronizedRootGroup section */',
            "\t\t{$ids['syncGroup']} /* WidgetsExtension */ = {\n"
            ."\t\t\tisa = PBXFileSystemSynchronizedRootGroup;\n"
            ."\t\t\tpath = WidgetsExtension;\n"
            ."\t\t\tsourceTree = \"<group>\";\n"
            ."\t\t};\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        if (! str_contains($content, '/* Begin PBXCopyFilesBuildPhase section */')) {
            $copyFilesSection = "/* Begin PBXCopyFilesBuildPhase section */\n/* End PBXCopyFilesBuildPhase section */\n\n";
            $content = preg_replace('/\/\* Begin PBXFileReference section \*\//', $copyFilesSection.'/* Begin PBXFileReference section */', $content, 1) ?? $content;
        }

        $result = $this->insertBeforeMarker(
            $content,
            '/* End PBXCopyFilesBuildPhase section */',
            "\t\t{$ids['copyPhase']} /* Embed App Extensions */ = {\n"
            ."\t\t\tisa = PBXCopyFilesBuildPhase;\n"
            ."\t\t\tbuildActionMask = 2147483647;\n"
            ."\t\t\tdstPath = \"\";\n"
            ."\t\t\tdstSubfolderSpec = 13;\n"
            ."\t\t\tfiles = (\n"
            ."\t\t\t\t{$ids['buildFile']} /* {$appexName} in Embed App Extensions */,\n"
            ."\t\t\t);\n"
            ."\t\t\tname = \"Embed App Extensions\";\n"
            ."\t\t\trunOnlyForDeploymentPostprocessing = 0;\n"
            ."\t\t};\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        $result = $this->insertBeforeMarker(
            $content,
            '/* End PBXFrameworksBuildPhase section */',
            "\t\t{$ids['frameworksPhase']} /* Frameworks */ = {\n"
            ."\t\t\tisa = PBXFrameworksBuildPhase;\n"
            ."\t\t\tbuildActionMask = 2147483647;\n"
            ."\t\t\tfiles = (\n"
            ."\t\t\t);\n"
            ."\t\t\trunOnlyForDeploymentPostprocessing = 0;\n"
            ."\t\t};\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        $result = $this->addLineToNamedGroupChildren(
            $content,
            'Products',
            "\t\t\t\t{$ids['fileRef']} /* {$appexName} */,\n"
        );
        if ($result !== null) {
            $content = $result;
        }

        $result = $this->insertBeforeMarker(
            $content,
            '/* End PBXNativeTarget section */',
            "\t\t{$ids['target']} /* {$targetName} */ = {\n"
            ."\t\t\tisa = PBXNativeTarget;\n"
            ."\t\t\tbuildConfigurationList = {$ids['configList']} /* Build configuration list for PBXNativeTarget \"{$targetName}\" */;\n"
            ."\t\t\tbuildPhases = (\n"
            ."\t\t\t\t{$ids['sourcesPhase']} /* Sources */,\n"
            ."\t\t\t\t{$ids['frameworksPhase']} /* Frameworks */,\n"
            ."\t\t\t\t{$ids['resourcesPhase']} /* Resources */,\n"
            ."\t\t\t);\n"
            ."\t\t\tbuildRules = (\n"
            ."\t\t\t);\n"
            ."\t\t\tdependencies = (\n"
            ."\t\t\t);\n"
            ."\t\t\tfileSystemSynchronizedGroups = (\n"
            ."\t\t\t\t{$ids['syncGroup']} /* WidgetsExtension */,\n"
            ."\t\t\t);\n"
            ."\t\t\tname = {$targetName};\n"
            ."\t\t\tpackageProductDependencies = (\n"
            ."\t\t\t);\n"
            ."\t\t\tproductName = {$targetName};\n"
            ."\t\t\tproductReference = {$ids['fileRef']} /* {$appexName} */;\n"
            ."\t\t\tproductType = \"com.apple.product-type.app-extension\";\n"
            ."\t\t};\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        $result = $this->addLineToProjectTargets(
            $content,
            "\t\t\t\t{$ids['target']} /* {$targetName} */,\n"
        );
        if ($result !== null) {
            $content = $result;
        }

        $result = $this->insertBeforeMarker(
            $content,
            '/* End PBXResourcesBuildPhase section */',
            "\t\t{$ids['resourcesPhase']} /* Resources */ = {\n"
            ."\t\t\tisa = PBXResourcesBuildPhase;\n"
            ."\t\t\tbuildActionMask = 2147483647;\n"
            ."\t\t\tfiles = (\n"
            ."\t\t\t);\n"
            ."\t\t\trunOnlyForDeploymentPostprocessing = 0;\n"
            ."\t\t};\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        $result = $this->insertBeforeMarker(
            $content,
            '/* End PBXSourcesBuildPhase section */',
            "\t\t{$ids['sourcesPhase']} /* Sources */ = {\n"
            ."\t\t\tisa = PBXSourcesBuildPhase;\n"
            ."\t\t\tbuildActionMask = 2147483647;\n"
            ."\t\t\tfiles = (\n"
            ."\t\t\t);\n"
            ."\t\t\trunOnlyForDeploymentPostprocessing = 0;\n"
            ."\t\t};\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        $result = $this->insertBeforeMarker(
            $content,
            '/* End PBXTargetDependency section */',
            "\t\t{$ids['targetDependency']} /* PBXTargetDependency */ = {\n"
            ."\t\t\tisa = PBXTargetDependency;\n"
            ."\t\t\ttarget = {$ids['target']} /* {$targetName} */;\n"
            ."\t\t\ttargetProxy = {$ids['containerProxy']} /* PBXContainerItemProxy */;\n"
            ."\t\t};\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        $result = $this->addLineToNamedTargetList(
            $content,
            $mainTargetName,
            'buildPhases',
            "\t\t\t\t{$ids['copyPhase']} /* Embed App Extensions */,\n"
        );
        if ($result !== null) {
            $content = $result;
        }

        $result = $this->addLineToNamedTargetList(
            $content,
            $mainTargetName,
            'dependencies',
            "\t\t\t\t{$ids['targetDependency']} /* PBXTargetDependency */,\n"
        );
        if ($result !== null) {
            $content = $result;
        }

        $result = $this->insertBeforeMarker(
            $content,
            '/* End XCBuildConfiguration section */',
            "\t\t{$ids['debugConfig']} /* Debug */ = {\n"
            ."\t\t\tisa = XCBuildConfiguration;\n"
            ."\t\t\tbuildSettings = {\n"
            ."\t\t\t\tAPPLICATION_EXTENSION_API_ONLY = YES;\n"
            ."\t\t\t\tCODE_SIGN_ENTITLEMENTS = WidgetsExtension/NativePHPWidgets.entitlements;\n"
            ."\t\t\t\tCODE_SIGN_STYLE = Automatic;\n"
            ."\t\t\t\tCURRENT_PROJECT_VERSION = 1;\n"
            ."\t\t\t\tGENERATE_INFOPLIST_FILE = YES;\n"
            ."\t\t\t\tINFOPLIST_FILE = WidgetsExtension/Info.plist;\n"
            ."\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = 16.0;\n"
            ."\t\t\t\tLD_RUNPATH_SEARCH_PATHS = (\n"
            ."\t\t\t\t\t\"$(inherited)\",\n"
            ."\t\t\t\t\t\"@executable_path/Frameworks\",\n"
            ."\t\t\t\t\t\"@executable_path/../../Frameworks\",\n"
            ."\t\t\t\t);\n"
            ."\t\t\t\tMARKETING_VERSION = 1.0;\n"
            ."\t\t\t\tNATIVEPHP_WIDGETS_APP_GROUP = {$appGroup};\n"
            ."\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = {$bundleId};\n"
            ."\t\t\t\tPRODUCT_NAME = \"$(TARGET_NAME)\";\n"
            ."\t\t\t\tSKIP_INSTALL = YES;\n"
            ."\t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;\n"
            ."\t\t\t\tSWIFT_VERSION = 5.0;\n"
            ."\t\t\t\tTARGETED_DEVICE_FAMILY = \"1,2\";\n"
            ."\t\t\t\tWIDGET_EXTENSION_KIND = NativePHPWidget;\n"
            ."\t\t\t};\n"
            ."\t\t\tname = Debug;\n"
            ."\t\t};\n"
            ."\t\t{$ids['releaseConfig']} /* Release */ = {\n"
            ."\t\t\tisa = XCBuildConfiguration;\n"
            ."\t\t\tbuildSettings = {\n"
            ."\t\t\t\tAPPLICATION_EXTENSION_API_ONLY = YES;\n"
            ."\t\t\t\tCODE_SIGN_ENTITLEMENTS = WidgetsExtension/NativePHPWidgets.entitlements;\n"
            ."\t\t\t\tCODE_SIGN_STYLE = Automatic;\n"
            ."\t\t\t\tCURRENT_PROJECT_VERSION = 1;\n"
            ."\t\t\t\tGENERATE_INFOPLIST_FILE = YES;\n"
            ."\t\t\t\tINFOPLIST_FILE = WidgetsExtension/Info.plist;\n"
            ."\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = 16.0;\n"
            ."\t\t\t\tLD_RUNPATH_SEARCH_PATHS = (\n"
            ."\t\t\t\t\t\"$(inherited)\",\n"
            ."\t\t\t\t\t\"@executable_path/Frameworks\",\n"
            ."\t\t\t\t\t\"@executable_path/../../Frameworks\",\n"
            ."\t\t\t\t);\n"
            ."\t\t\t\tMARKETING_VERSION = 1.0;\n"
            ."\t\t\t\tNATIVEPHP_WIDGETS_APP_GROUP = {$appGroup};\n"
            ."\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = {$bundleId};\n"
            ."\t\t\t\tPRODUCT_NAME = \"$(TARGET_NAME)\";\n"
            ."\t\t\t\tSKIP_INSTALL = YES;\n"
            ."\t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;\n"
            ."\t\t\t\tSWIFT_VERSION = 5.0;\n"
            ."\t\t\t\tTARGETED_DEVICE_FAMILY = \"1,2\";\n"
            ."\t\t\t\tWIDGET_EXTENSION_KIND = NativePHPWidget;\n"
            ."\t\t\t};\n"
            ."\t\t\tname = Release;\n"
            ."\t\t};\n"
        );

        if ($result === null) {
            return null;
        }

        $content = $result;

        $result = $this->insertBeforeMarker(
            $content,
            '/* End XCConfigurationList section */',
            "\t\t{$ids['configList']} /* Build configuration list for PBXNativeTarget \"{$targetName}\" */ = {\n"
            ."\t\t\tisa = XCConfigurationList;\n"
            ."\t\t\tbuildConfigurations = (\n"
            ."\t\t\t\t{$ids['debugConfig']} /* Debug */,\n"
            ."\t\t\t\t{$ids['releaseConfig']} /* Release */,\n"
            ."\t\t\t);\n"
            ."\t\t\tdefaultConfigurationIsVisible = 0;\n"
            ."\t\t\tdefaultConfigurationName = Release;\n"
            ."\t\t};\n"
        );

        if ($result === null) {
            return null;
        }

        return $this->insertBeforeMarker(
            $result,
            'rootObject =',
            "\t/* ".self::AUTOGEN_MARKER." */\n"
        );
    }

    private function addLineToNamedGroupChildren(string $content, string $groupName, string $line): ?string
    {
        $groupName = preg_quote($groupName, '/');
        $pattern = "/(\s+[A-F0-9]{24} \/\\* {$groupName} \\*\/ = \{\n.*?\n\s+children = \(\n)(.*?)(\s+\);\n)/s";

        $updated = preg_replace_callback($pattern, function (array $matches) use ($line) {
            if (str_contains($matches[2], trim($line))) {
                return $matches[0];
            }

            return $matches[1].$matches[2].$line.$matches[3];
        }, $content, 1, $count);

        return $count > 0 ? $updated : null;
    }

    private function addLineToNamedTargetList(string $content, string $targetName, string $listName, string $line): ?string
    {
        $targetName = preg_quote($targetName, '/');
        $listName = preg_quote($listName, '/');
        $pattern = "/(\s+[A-F0-9]{24} \/\\* {$targetName} \\*\/ = \{\n.*?\n\s+{$listName} = \(\n)(.*?)(\s+\);\n)/s";

        $updated = preg_replace_callback($pattern, function (array $matches) use ($line) {
            if (str_contains($matches[2], trim($line))) {
                return $matches[0];
            }

            return $matches[1].$matches[2].$line.$matches[3];
        }, $content, 1, $count);

        return $count > 0 ? $updated : null;
    }

    private function addLineToProjectTargets(string $content, string $line): ?string
    {
        $pattern = "/(\s+[A-F0-9]{24} \/\\* Project object \\*\/ = \{\n.*?\n\s+targets = \(\n)(.*?)(\s+\);\n)/s";

        $updated = preg_replace_callback($pattern, function (array $matches) use ($line) {
            if (str_contains($matches[2], trim($line))) {
                return $matches[0];
            }

            return $matches[1].$matches[2].$line.$matches[3];
        }, $content, 1, $count);

        return $count > 0 ? $updated : null;
    }

    private function insertBeforeMarker(string $content, string $marker, string $insert): ?string
    {
        $position = strpos($content, $marker);

        if ($position === false) {
            return null;
        }

        return substr($content, 0, $position).$insert.substr($content, $position);
    }

    private function detectProjectObjectId(string $content): ?string
    {
        if (preg_match('/^\s*([A-F0-9]{24}) \/\* Project object \*\/ = \{/m', $content, $matches)) {
            return $matches[1];
        }

        return null;
    }

    private function detectMainTargetName(string $content): ?string
    {
        if (! preg_match_all('/\s+([A-F0-9]{24}) \/\* ([^*]+) \*\/ = \{\n(.*?)\s+\};\n/s', $content, $blocks, PREG_SET_ORDER)) {
            return null;
        }

        foreach ($blocks as $block) {
            $body = $block[3];

            if (! str_contains($body, 'isa = PBXNativeTarget;')) {
                continue;
            }

            if (str_contains($body, 'productType = "com.apple.product-type.application";')) {
                return trim($block[2]);
            }
        }

        return null;
    }

    private function objectId(string $seed): string
    {
        return strtoupper(substr(md5('mobile-widgets-'.$this->appId().'-'.$seed), 0, 24));
    }
}
